name: Build, lint, test

on:
  push:

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Build (TypeScript)
        run: npm run build

      - name: Run ESLint
        run: npm run lint

      - name: Run tests with coverage
        uses: jwalton/gh-find-current-pr@v1
        id: findPr

      - name: Run tests with coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          prnumber: ${{ steps.findPr.outputs.number }}
